[package]
name = "cobs"
version = "0.1.3"
authors = ["Allen Welkie <>"]
license = "MIT OR Apache-2.0"
description = """
    This is an implementation of the Consistent Overhead Byte Stuffing (COBS) algorithm.
    COBS is an algorithm for transforming a message into an encoding where a specific value
    (the "sentinel" value) is not used. This value can then be used to mark frame boundaries
    in a serial communication channel. """
repository = "https://github.com/awelkie/cobs.rs"
keywords = ["consistent", "overhead", "byte", "stuffing"]

[features]
default = ["use_std"]
use_std = []

[dev-dependencies]
quickcheck = "^0.5.0"
bencher = "0.1.5"
rand = "0.6.0"


[[bench]]
name = "benchmark"
harness = false
